
import { Theme } from '@/types/theme';

export const additionalThemes: Omit<Theme, 'id' | 'sections' | 'status' | 'isDefault' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Ocean Breeze',
    description: 'A refreshing coastal theme with ocean blues and sandy neutrals',
    primaryColor: '#0077be',
    secondaryColor: '#00a8cc',
    accentColor: '#ff6b35',
    backgroundColor: '#f8fcff',
    textColor: '#2c3e50',
    cardColor: '#ffffff',
    borderColor: '#e1f4fd',
    gradientFrom: '#0077be',
    gradientTo: '#00a8cc',
    fontFamily: 'Poppins',
    category: 'modern',
    headerStyle: 'modern',
    footerStyle: 'clean',
    buttonStyle: 'rounded',
    cardStyle: 'shadow',
    layout: 'modern'
  },
  {
    name: 'Sunset Glow',
    description: 'A warm and inviting theme with sunset-inspired colors',
    primaryColor: '#d63384',
    secondaryColor: '#fd7e14',
    accentColor: '#ffc107',
    backgroundColor: '#fff8e1',
    textColor: '#5d4037',
    cardColor: '#ffffff',
    borderColor: '#ffecb3',
    gradientFrom: '#d63384',
    gradientTo: '#fd7e14',
    fontFamily: 'Roboto',
    category: 'warm',
    headerStyle: 'elegant',
    footerStyle: 'warm',
    buttonStyle: 'rounded',
    cardStyle: 'elevated',
    layout: 'traditional'
  },
  {
    name: 'Forest Explorer',
    description: 'An earthy theme perfect for nature and adventure travel',
    primaryColor: '#2d5016',
    secondaryColor: '#558b2f',
    accentColor: '#ff9800',
    backgroundColor: '#f1f8e9',
    textColor: '#33691e',
    cardColor: '#ffffff',
    borderColor: '#c8e6c9',
    gradientFrom: '#2d5016',
    gradientTo: '#558b2f',
    fontFamily: 'Inter',
    category: 'nature',
    headerStyle: 'bold',
    footerStyle: 'dark',
    buttonStyle: 'square',
    cardStyle: 'border',
    layout: 'creative'
  },
  {
    name: 'Urban Chic',
    description: 'A sleek metropolitan theme with modern sophistication',
    primaryColor: '#37474f',
    secondaryColor: '#546e7a',
    accentColor: '#26c6da',
    backgroundColor: '#fafafa',
    textColor: '#263238',
    cardColor: '#ffffff',
    borderColor: '#eceff1',
    gradientFrom: '#37474f',
    gradientTo: '#546e7a',
    fontFamily: 'Roboto',
    category: 'modern',
    headerStyle: 'minimal',
    footerStyle: 'clean',
    buttonStyle: 'square',
    cardStyle: 'flat',
    layout: 'minimal'
  },
  {
    name: 'Royal Elegance',
    description: 'A luxurious theme with royal purples and gold accents',
    primaryColor: '#4a148c',
    secondaryColor: '#7b1fa2',
    accentColor: '#ffd700',
    backgroundColor: '#faf0ff',
    textColor: '#4a148c',
    cardColor: '#ffffff',
    borderColor: '#e1bee7',
    gradientFrom: '#4a148c',
    gradientTo: '#7b1fa2',
    fontFamily: 'Playfair Display',
    category: 'luxury',
    headerStyle: 'elegant',
    footerStyle: 'luxury',
    buttonStyle: 'pill',
    cardStyle: 'glass',
    layout: 'luxury'
  },
  {
    name: 'Arctic Frost',
    description: 'A cool, crisp theme with winter-inspired whites and blues',
    primaryColor: '#1e3a8a',
    secondaryColor: '#3b82f6',
    accentColor: '#06b6d4',
    backgroundColor: '#f8fafc',
    textColor: '#1e293b',
    cardColor: '#ffffff',
    borderColor: '#cbd5e1',
    gradientFrom: '#1e3a8a',
    gradientTo: '#3b82f6',
    fontFamily: 'Inter',
    category: 'modern',
    headerStyle: 'modern',
    footerStyle: 'clean',
    buttonStyle: 'rounded',
    cardStyle: 'shadow',
    layout: 'modern'
  },
  {
    name: 'Desert Sand',
    description: 'A warm, earthy theme inspired by desert landscapes',
    primaryColor: '#92400e',
    secondaryColor: '#d97706',
    accentColor: '#dc2626',
    backgroundColor: '#fef7ed',
    textColor: '#78716c',
    cardColor: '#ffffff',
    borderColor: '#fed7aa',
    gradientFrom: '#92400e',
    gradientTo: '#d97706',
    fontFamily: 'Roboto',
    category: 'warm',
    headerStyle: 'modern',
    footerStyle: 'warm',
    buttonStyle: 'square',
    cardStyle: 'elevated',
    layout: 'creative'
  },
  {
    name: 'Midnight Galaxy',
    description: 'A sophisticated dark theme with cosmic accents',
    primaryColor: '#1f2937',
    secondaryColor: '#374151',
    accentColor: '#8b5cf6',
    backgroundColor: '#111827',
    textColor: '#f9fafb',
    cardColor: '#1f2937',
    borderColor: '#374151',
    gradientFrom: '#1f2937',
    gradientTo: '#8b5cf6',
    fontFamily: 'Inter',
    category: 'modern',
    headerStyle: 'modern',
    footerStyle: 'clean',
    buttonStyle: 'rounded',
    cardStyle: 'flat',
    layout: 'modern'
  },
  {
    name: 'Tropical Paradise',
    description: 'Vibrant tropical colors for exotic destinations',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    accentColor: '#f59e0b',
    backgroundColor: '#f0fdfa',
    textColor: '#064e3b',
    cardColor: '#ffffff',
    borderColor: '#a7f3d0',
    gradientFrom: '#059669',
    gradientTo: '#10b981',
    fontFamily: 'Poppins',
    category: 'modern',
    headerStyle: 'modern',
    footerStyle: 'clean',
    buttonStyle: 'rounded',
    cardStyle: 'elevated',
    layout: 'creative'
  },
  {
    name: 'Classic Heritage',
    description: 'A timeless theme with traditional elegance',
    primaryColor: '#7c2d12',
    secondaryColor: '#b45309',
    accentColor: '#dc2626',
    backgroundColor: '#fefdf8',
    textColor: '#451a03',
    cardColor: '#ffffff',
    borderColor: '#f3e8ff',
    gradientFrom: '#7c2d12',
    gradientTo: '#b45309',
    fontFamily: 'Playfair Display',
    category: 'luxury',
    headerStyle: 'elegant',
    footerStyle: 'luxury',
    buttonStyle: 'pill',
    cardStyle: 'glass',
    layout: 'traditional'
  },
  {
    name: 'Neon Cyber',
    description: 'A futuristic theme with electric neon accents',
    primaryColor: '#0f172a',
    secondaryColor: '#1e293b',
    accentColor: '#00ff88',
    backgroundColor: '#020617',
    textColor: '#e2e8f0',
    cardColor: '#1e293b',
    borderColor: '#334155',
    gradientFrom: '#0f172a',
    gradientTo: '#00ff88',
    fontFamily: 'Inter',
    category: 'modern',
    headerStyle: 'modern',
    footerStyle: 'dark',
    buttonStyle: 'square',
    cardStyle: 'glow',
    layout: 'futuristic'
  },
  {
    name: 'Cherry Blossom',
    description: 'A delicate theme inspired by Japanese spring',
    primaryColor: '#be185d',
    secondaryColor: '#ec4899',
    accentColor: '#f97316',
    backgroundColor: '#fdf2f8',
    textColor: '#7c2d12',
    cardColor: '#ffffff',
    borderColor: '#fce7f3',
    gradientFrom: '#be185d',
    gradientTo: '#ec4899',
    fontFamily: 'Playfair Display',
    category: 'elegant',
    headerStyle: 'elegant',
    footerStyle: 'clean',
    buttonStyle: 'rounded',
    cardStyle: 'soft',
    layout: 'minimal'
  },
  {
    name: 'Golden Hour',
    description: 'Warm golden tones capturing the perfect sunset',
    primaryColor: '#b45309',
    secondaryColor: '#f59e0b',
    accentColor: '#dc2626',
    backgroundColor: '#fffbeb',
    textColor: '#7c2d12',
    cardColor: '#ffffff',
    borderColor: '#fde68a',
    gradientFrom: '#b45309',
    gradientTo: '#f59e0b',
    fontFamily: 'Roboto',
    category: 'warm',
    headerStyle: 'bold',
    footerStyle: 'warm',
    buttonStyle: 'rounded',
    cardStyle: 'elevated',
    layout: 'creative'
  },
  {
    name: 'Emerald Dreams',
    description: 'Rich emerald greens with luxurious accents',
    primaryColor: '#047857',
    secondaryColor: '#059669',
    accentColor: '#f59e0b',
    backgroundColor: '#f0fdf4',
    textColor: '#064e3b',
    cardColor: '#ffffff',
    borderColor: '#bbf7d0',
    gradientFrom: '#047857',
    gradientTo: '#059669',
    fontFamily: 'Playfair Display',
    category: 'luxury',
    headerStyle: 'elegant',
    footerStyle: 'luxury',
    buttonStyle: 'pill',
    cardStyle: 'glass',
    layout: 'luxury'
  },
  {
    name: 'Storm Cloud',
    description: 'Dramatic grays with electric blue highlights',
    primaryColor: '#374151',
    secondaryColor: '#6b7280',
    accentColor: '#3b82f6',
    backgroundColor: '#f9fafb',
    textColor: '#1f2937',
    cardColor: '#ffffff',
    borderColor: '#e5e7eb',
    gradientFrom: '#374151',
    gradientTo: '#6b7280',
    fontFamily: 'Inter',
    category: 'modern',
    headerStyle: 'bold',
    footerStyle: 'dark',
    buttonStyle: 'square',
    cardStyle: 'shadow',
    layout: 'modern'
  }
];
